<?php

$title = 'Suppression';
$url   = $this->url('product', ['action' => 'supprimerProduitPanier', 'id' => $id]);

$this->headTitle($title);

?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    Es-tu sûr de vouloir supprimer le produit suivant : 
    "<?= $this->escapeHtml($product->nom) ?>"
    "<?= $this->escapeHtml($product->description) ?>"
    "<?= $this->escapeHtml($product->prix) ?>" ?
</p>
<form action="<?= $url ?>" method="post">
    <div class="form-group">
        <input type="hidden" name="id" value="<?= (int) $product->id ?>" />
        <input type="submit" class="btn btn-danger" name="del" value="Oui" />
        <input type="submit" class="btn btn-success" name="del" value="Non" />
    </div>
</form>