<?php

$title = 'Produit ajouté au panier';
$this->headTitle($title);

?>
<h1><?= $this->escapeHtml($title) ?></h1>

<h3>Vous avez ajouté le produit suivant au panier :</h3>

<div class="card" style="width: 18rem;" xmlns=""><img class="card-img-top" src="http://lorempixel.com/250/250/" alt="Card image cap">
    <div class="card-body"><h5 class="card-title"><?= $this->escapeHtml($ajoutPanier->nom) ?></h5>
        <p class="card-text"><?= $this->escapeHtml($ajoutPanier->description) ?></p>
        <p class="card-texte"><?= $this->escapeHtml($ajoutPanier->prix) ?></p>

    </div>
</div>
<a href="<?= $this->url('product', ['action' => 'Index']) ?>">revenir au catalogue</a>
<a href="<?= $this->url('product', ['action' => 'IndexPanier']) ?>">Accéder à votre panier</a>