<?php

$title = 'Produit ajouté au panier';
$this->headTitle($title);

?>
<h1><?= $this->escapeHtml($title) ?></h1>

<h3>Vous avez ajouté le produit suivant au panier :</h3>

<div class="card" style="width: 18rem;" xmlns=""><img class="card-img-top" src="http://lorempixel.com/250/250/" alt="Card image cap">
    <div class="card-body"><h5 class="card-title"><b>Nom : </b><?= $this->escapeHtml($ajoutPanier->nom) ?></h5>
        <p class="card-text"><b>Description : </b><?= $this->escapeHtml($ajoutPanier->description) ?></p>
        <p class="card-text"><b>Prix : </b><?= $this->escapeHtml($ajoutPanier->prix) ?> €</p>

    </div>
</div>
<a href="<?= $this->url('product', ['action' => 'Index']) ?>"><button class="btn btn-dark"><i class="fas fa-undo-alt"></i>Revenir au catalogue</button></a>
<a href="<?= $this->url('product', ['action' => 'IndexPanier']) ?>"><button class="btn btn-dark"><i class="fas fa-cart-arrow-down"></i>Accéder à votre panier</button></a>