<?php

$title = 'Détails du produit';
$this->headTitle($title);

?>
<h1><?= $this->escapeHtml($title) ?></h1>


<div class="card" style="width: 18rem;" xmlns=""><img class="card-img-top" src="http://lorempixel.com/250/250/" alt="Card image cap">
    <div class="card-body"><h5 class="card-title"><b>Nom : </b><?= $this->escapeHtml($details->nom) ?></h5>
        <p class="card-text"><b>Description : </b><?= $this->escapeHtml($details->description) ?></p>
        <p class="card-text"><b>Prix : </b><?= $this->escapeHtml($details->prix) ?> €</p>
        <p class="card-text"><a href="<?= $this->url('product', ['action' => 'AjoutPanier', 'id' => $details->id]) ?>"><button class="btn btn-dark"><i class="fas fa-cart-plus"></i>Ajouter au panier</button></a></p>
    </div>
</div>