<?php

$title = 'détails du produit';
$this->headTitle($title);

?>
<h1><?= $this->escapeHtml($title) ?></h1>


<div class="card" style="width: 18rem;" xmlns=""><img class="card-img-top" src="http://lorempixel.com/250/250/" alt="Card image cap">
    <div class="card-body"><h5 class="card-title"><?= $this->escapeHtml($details->nom) ?></h5>
        <p class="card-text"><?= $this->escapeHtml($details->description) ?></p>
        <p class="card-texte"><?= $this->escapeHtml($details->prix) ?></p>
        <p class="card-texte"><td><a href="<?= $this->url('product', ['action' => 'AjoutPanier', 'id' => $details->id]) ?>">Ajouter au panier</a></td></button></td></p>
    </div>
</div>