<?php

$title = 'Modifier le produit';
$this->headTitle($title);

?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php

$album = $form->get('nom');
$album->setAttribute('class', 'form-control');
$album->setAttribute('placeholder', 'nom du produit');

$artist = $form->get('description');
$artist->setAttribute('class', 'form-control');
$artist->setAttribute('placeholder', 'description du produit');

$prix = $form->get('prix');
$prix->setAttribute('class', 'form-control');
$prix->setAttribute('placeholder', 'prix du produit');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-dark');

$form->setAttribute('action', $this->url('product', [
    'action' => 'edit',
    'id'     => $id,
]));

$form->prepare();

echo $this->form()->openTag($form);

?>
    <div class="form-group">
        <?= $this->formLabel($album) ?>
        <?= $this->formElement($album) ?>
        <?= $this->formElementErrors()->render($album, ['class' => 'help-block']) ?>
    </div>
    <div class="form-group">
        <?= $this->formLabel($artist) ?>
        <?= $this->formElement($artist) ?>
        <?= $this->formElementErrors()->render($artist, ['class' => 'help-block']) ?>
    </div>
    <div class="form-group">
        <?= $this->formLabel($prix) ?>
        <?= $this->formElement($prix) ?>
        <?= $this->formElementErrors()->render($prix, ['class' => 'help-block']) ?>
    </div>
<?php

echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();

?>