<?php
$title = 'Détails de votre Panier';
$this->headTitle($title);
$tot =0;
$tot_tax = 0;


?>
<h1><?= $this->escapeHtml($title) ?></h1>
<table class="table">
    <tr>
        <th>Nom</th>
        <th>Description</th>
        <th>Prix</th>
        <th>Prix taxe incluse</th>
        <th>Supprimer</th>
    </tr>
    <?php foreach ($panier as $prod) { ?>
        <?php $taxe =($prod->prix *0.05)+ ($prod->prix*0.09975) +($prod->prix);
        $tot += $prod->prix;
        $tot_tax += $taxe;
        ?>
        <tr>
            <td><?= $this->escapeHtml($prod->nom) ?></td>
            <td><?= $this->escapeHtml($prod->description) ?></td>
            <td><?= $this->escapeHtml($prod->prix) ?> €</td>
            <td><?= $this->escapeHtml($taxe) ?> €</td>
            <td><a href="<?= $this->url('product', ['action' => 'supprimerProduitPanier','id' => $prod->id]) ?>"><i title ="Supprimer" class="fas fa-trash-alt red"></a></td>
        </tr>
    <?php } ?>

</table>
<br/> Total de la transaction : <?= $this->escapeHtml($tot) ?> €
<br/> Total taxe incluse : <?= $this->escapeHtml($tot_tax) ?> €

<br/><a href="<?= $this->url('product', ['action' => 'PayerPanier']) ?>"><button class="btn btn-dark"><i class="fab fa-paypal"></i>Effectuer la transaction</button></a> <a href="<?= $this->url('product', ['action' => 'Index']) ?>"><button class="btn btn-dark"><i class="fas fa-undo-alt"></i>Revenir au catalogue</button></a>